spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/portal_bd?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
      auto-commit: true